from pathlib import Path

TARGET_YEAR = 2568
MAX_FACTOR_UPLIFT = 0.15
DEFAULT_CAP_LIMIT = 6_000_000_000

DATA_DIR = Path("data")
FILES = {
    "damage": "ข้อมูลโอกาสเกิดความเสียหาย (1).xlsx",
    "rmms": "แผนงาน RMMS.xlsx",
    "cluster": "cluster_district.xlsx",
    "group": "group_data_final.xlsx",
    "operating_distances": "operating_distances.xlsx",
    "bridge_bmms": "bridge_bmms.xlsx",
}

CLUSTER_GRASS_FORMULA = {
    0: {"slope": 7623.5896, "intercept": 1915806.6067},
    1: {"slope": 10742.3944, "intercept": 7303610.9973},
    2: {"slope": 28697.5085, "intercept": 2988185.5760},
}

# สูตรหลัก: quantity * damage_probability * unit_cost + factor + fixed cost
# สามารถแก้ quantity_col, damage_probability, unit_cost, factor profile ได้ที่นี่
WORKLOAD_CONFIG = [
    {
        "item": "ผิวจราจร/ระยะทางต่อ 2 ช่องจราจร",
        "category": "Asset",
        "quantity_col": "length_to2",
        "unit": "กม.",
        "damage_key": None,
        "damage_probability": 1.0,
        "unit_cost": 50000.0,
        "apply_damage_probability": True,
        "condition_profile": "pavement_custom",
        "note": "ราคากลางเริ่มต้น 50,000 บาท และโอกาสเกิดความเสียหาย 1.0 ตามตารางข้อมูลใหม่",
    },
    {
        "item": "เกาะกลาง",
        "category": "Asset",
        "quantity_col": "road_medians_m",
        "unit": "เมตร",
        "damage_key": "เกาะกลาง",
        "damage_probability": 1.0,
        "unit_cost": 30.0,
        "apply_damage_probability": True,
        "condition_profile": "median_custom",
        "note": "ราคากลางเริ่มต้น 30 บาท และโอกาสเกิดความเสียหาย 1.0 ตามตารางข้อมูลใหม่",
    },
    {
        "item": "สะพานลอยคนเดินข้าม",
        "category": "Asset",
        "quantity_col": "asset_pedestrian_bridge_num",
        "unit": "แห่ง",
        "damage_key": "สะพานลอยคนเดิน",
        "damage_probability": 0.02,
        "unit_cost": 5000.0,
        "condition_profile": "none",
        "note": "ราคากลางเริ่มต้น 5,000 บาท และโอกาสเกิดความเสียหาย 0.02 ตามตารางข้อมูลใหม่",
    },
    {
        "item": "สะพานข้ามคลอง < 20 ม.",
        "category": "Asset",
        "quantity_col": "bridge_count",
        "unit": "แห่ง",
        "damage_key": "สะพานทางยกระดับ",
        "damage_probability": 0.04,
        "unit_cost": 500.0,
        "condition_profile": "short_bridge_custom",
        "note": "ราคากลางเริ่มต้น 500.0 บาท/แห่ง และจำนวนสะพาน < 20 ม. ดึงจากไฟล์ bridge_bmms.xlsx",
    },
    {
        "item": "ท่อลอด",
        "category": "Asset",
        "quantity_col": "input_pipebridge_v",
        "unit": "แห่ง/ช่อง",
        "damage_key": "สะพานทางยกระดับ",
        "unit_cost": 500.0,
        "condition_profile": "bridge_custom",
        "note": "ถ้าไม่มีข้อมูล pipebridge_v จะเป็น 0",
    },
    {
        "item": "ศาลาทางหลวง",
        "category": "Asset",
        "quantity_col": "asset_pavilion_num",
        "unit": "แห่ง",
        "damage_key": "ศาลา",
        "damage_probability": 0.5,
        "unit_cost": 4000.0,
        "condition_profile": "none",
        "note": "ราคากลางเริ่มต้น 4,000 บาท และโอกาสเกิดความเสียหาย 0.5 ตามตารางข้อมูลใหม่",
    },
    {
        "item": "ไฟจราจร",
        "category": "Asset",
        "quantity_col": "asset_traffic_light_num",
        "unit": "ต้น",
        "damage_key": "ไฟจราจร",
        "unit_cost": 40000.0,
        "condition_profile": "traffic_asset_custom",
        "note": "ใช้ probability หน่วยต้น",
    },
    {
        "item": "ไฟทางข้าม",
        "category": "Asset",
        "quantity_col": "asset_ped_cross_light_num",
        "unit": "ชุด",
        "damage_key": "ไฟทางข้าม",
        "unit_cost": 3500.0,
        "condition_profile": "traffic_asset_custom",
        "note": "ราคากลางเริ่มต้น 3,500 บาท ตามตารางข้อมูลใหม่",
    },
    {
        "item": "ไฟแสงสว่างกิ่งเดี่ยวกิ่งคู่",
        "category": "Asset",
        "quantity_col": "asset_street_light_num",
        "unit": "ต้น",
        "damage_key": "ไฟแสงสว่างกิ่งเดี่ยวกิ่งคู่",
        "unit_cost": 550.0,
        "condition_profile": "traffic_asset_custom",
        "note": "ราคากลางเริ่มต้น 550 บาท ตามตารางข้อมูลใหม่",
    },
    {
        "item": "ไฟแสงสว่าง Hi-Mast",
        "category": "Asset",
        "quantity_col": "hi_mast_num",
        "unit": "ต้น",
        "damage_key": "ไฟแสงสว่าง Hi-Mast",
        "unit_cost": 3000.0,
        "condition_profile": "traffic_asset_custom",
        "note": "ราคากลางเริ่มต้น 3,000 บาท ตามตารางข้อมูลใหม่",
    },
    {
        "item": "ไฟกระพริบ",
        "category": "Asset",
        "quantity_col": "asset_flashing_light_num",
        "unit": "ชุด",
        "damage_key": "ไฟกระพริบ",
        "unit_cost": 3500.0,
        "condition_profile": "traffic_asset_custom",
        "note": "ราคากลางเริ่มต้น 3,500 บาท ตามตารางข้อมูลใหม่",
    },
    {
        "item": "ป้ายจราจร",
        "category": "Asset",
        "quantity_col": "input_traffic_sign_num",
        "unit": "ป้าย",
        "damage_key": "ป้ายจราจร",
        "unit_cost": 20.0,
        "condition_profile": "traffic_asset_custom",
        "note": "ราคากลางเริ่มต้น 20 บาท ตามตารางข้อมูลใหม่",
    },
    {
        "item": "ท่อระบายน้ำ",
        "category": "Asset",
        "quantity_col": "asset_drainage_pipe_num",
        "unit": "แห่ง",
        "damage_key": "ท่อระบายน้ำ",
        "damage_probability": 0.7,
        "unit_cost": 500.0,
        "condition_profile": "drainage_pipe_custom",
        "note": "ราคากลางเริ่มต้น 500 บาท และโอกาสเกิดความเสียหาย 0.7 ตามตารางข้อมูลใหม่",
    },
    {
        "item": "ทางระบายน้ำ",
        "category": "Asset",
        "quantity_col": "input_drainage_m",
        "unit": "เมตร",
        "damage_key": "ท่อระบายน้ำ",
        "damage_probability": 0.5,
        "unit_cost": 25.0,
        "condition_profile": "drainage_ditch_custom",
        "note": "ราคากลางเริ่มต้น 25 บาท และโอกาสเกิดความเสียหาย 0.5 ตามตารางข้อมูลใหม่",
    },
    {
        "item": "งานตัดหญ้าและบำรุงรักษาเขตทาง",
        "category": "Asset",
        "quantity_col": "grass_mowing_qty",
        "unit": "กม.",
        "damage_key": None,
        "damage_probability": None,
        "unit_cost": None,
        "apply_damage_probability": False,
        "condition_profile": "none",
        "note": "ดึงราคากลางเริ่มต้นตาม Cluster ของแขวง (ไม่มีการคูณโอกาสเกิดความเสียหาย)",
    },
    {
        "item": "งานตีเส้นจราจร",
        "category": "Asset",
        "quantity_col": "roadmarking_sqm",
        "unit": "ตร.ม.",
        "damage_key": None,
        "damage_probability": 0.5,
        "unit_cost": 60.0,
        "apply_damage_probability": True,
        "condition_profile": "none",
        "note": "จาก ASSET (roadmarking_sqm)",
    },
    {
        "item": "อุโมงค์/ทางลอด",
        "category": "Asset",
        "quantity_col": "underpass_m",
        "unit": "เมตร",
        "damage_key": None,
        "damage_probability": 1.0,
        "unit_cost": 6000.0,
        "apply_damage_probability": False,
        "condition_profile": "none",
        "note": "จาก ASSET (underpass_m)",
    },
    {
        "item": "ทางเท้า",
        "category": "Asset",
        "quantity_col": "sidewalk_sqm",
        "unit": "ตร.ม.",
        "damage_key": "ทางเท้า",
        "damage_probability": 0.1392,
        "unit_cost": 200.0,
        "apply_damage_probability": True,
        "condition_profile": "none",
        "note": "จาก ASSET (sidewalk_sqm)",
    },
    {
        "item": "ทางจักรยาน",
        "category": "Asset",
        "quantity_col": "bicyclelane_sqm",
        "unit": "ตร.ม.",
        "damage_key": "ทางจักรยาน",
        "damage_probability": 0.0,
        "unit_cost": 50.0,
        "apply_damage_probability": True,
        "condition_profile": "none",
        "note": "จาก ASSET (bicyclelane_sqm)",
    },
    {
        "item": "ราวกันอันตราย",
        "category": "Asset",
        "quantity_col": "guardrail_m",
        "unit": "เมตร",
        "damage_key": None,
        "damage_probability": 1.0,
        "unit_cost": 50.0,
        "apply_damage_probability": False,
        "condition_profile": "none",
        "note": "จาก ASSET (guardrail_m)",
    },
    {
        "item": "หลักนำทาง/หลัก กม.",
        "category": "Asset",
        "quantity_col": "guidepost_num",
        "unit": "ต้น",
        "damage_key": None,
        "damage_probability": 1.0,
        "unit_cost": 0.0,
        "apply_damage_probability": False,
        "condition_profile": "none",
        "note": "จาก ASSET (guidepost_num)",
    },
]

FACTOR_PROFILES = {
    "none": {},
    "pavement_custom": {"traffic_score": 1.0, "truck_score": 1.0, "rain_score": 1.0, "operating_distance_score": 1.0},
    "median_custom": {"traffic_score": 1.0, "rain_score": 1.0},
    "drainage_pipe_custom": {"rain_score": 1.0, "elevation_score": 1.0},
    "drainage_ditch_custom": {"traffic_score": 1.0, "rain_score": 1.0},
    "bridge_custom": {"traffic_score": 1.0, "truck_score": 1.0},
    "short_bridge_custom": {"traffic_score": 1.0, "truck_score": 1.0, "rain_score": 1.0},
    "traffic_asset_custom": {"traffic_score": 1.0},
}
